### ISSUE TITLE
Add jmxs protocol to Readme

### ISSUE THREAD

**Issue by fa-dtavares** [seuf/zabbix_java#2]
I found I needed jmxs protocol to support SSL Jmx and SSL RMI. I recommend you update the Readme to include jmxs as a protocol option as the code shows it's available.

**Comment by seuf** [comment]
You can now use the latest zabbix 3.4 version which can override jmx endpoint for each jmx item.

**Comment by seuf** [comment]
I've added the jmxs protocol in ready.
